baseurl = "https://nikstar.me/"
#canonifyUrls = true
languageCode = "en-us"
title = "nikstar/blog"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[params]
	description = "The blog by Nikita (@nikstar) about machine learning, hacking, Telegram and other stuff I have not found yet"
	author = "Nikita Starshinov"

[markup.goldmark.renderer]
unsafe= true
